{% set name = "socketIO-client-nexus" %}
{% set version = "0.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41e6aaaff981f6729690f472eb2c7a5d1dda07349077e34444527b9700b0aea5

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests >=2.7.0
    - six
    - websocket-client

test:
  requires:
    - python {{ python_min }}
  imports:
    - socketIO_client_nexus

about:
  home: https://github.com/nexus-devs/socketIO-client-2.0.3
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A socket.io 2.x client library for Python'

  description: |
    A socket.io 2.x client library for Python
  dev_url: https://github.com/nexus-devs/socketIO-client-2.0.3

extra:
  recipe-maintainers:
    - timkpaine
